DELIMITER /

DROP PROCEDURE IF EXISTS PARTICLE/
	CREATE PROCEDURE PARTICLE (IN VDATE_PUBLICATION DATE, IN VRATE_POSITIVITY FLOAT,
	IN VRATE_NEGATIVITY FLOAT, IN VRATE_JOY FLOAT, IN VRATE_FEAR FLOAT, IN VRATE_SADNESS FLOAT,
	IN VRATE_ANGRY FLOAT, IN VRATE_SURPRISE FLOAT, IN VRATE_DISGUSS FLOAT, IN VNEWSPAPER VARCHAR(25), OUT VID_ARTICLE INT)

BEGIN
	
	DECLARE VID_NEWSPAPER INT;

	SELECT id_newspaper INTO VID_NEWSPAPER
    FROM newspaper
    WHERE newspaper.name_newspaper = VNEWSPAPER;
	
    IF (VID_NEWSPAPER IS NULL)  THEN 
		
		INSERT INTO newspaper (id_newspaper, name_newspaper, link_newspaper, link_logo) 
		VALUES (NULL, VNEWSPAPER, NULL, NULL);
    	
    	SELECT LAST_INSERT_ID() INTO VID_NEWSPAPER;
	
	END IF;

	INSERT INTO article(id_article, date_publication, rate_positivity, rate_negativity, rate_joy, 
	rate_fear, rate_sadness, rate_angry, rate_surprise, rate_disgust, id_newspaper) VALUES (NULL,VDATE_PUBLICATION,VRATE_POSITIVITY,VRATE_NEGATIVITY,VRATE_JOY,VRATE_FEAR,
	VRATE_SADNESS,VRATE_ANGRY,VRATE_SURPRISE,VRATE_DISGUSS,VID_NEWSPAPER);
	
	SELECT LAST_INSERT_ID() INTO vid_article;

END/ 

DELIMITER ;
Call PARTICLE('1994-12-10',0.1,0.1,0.1,0.1,0.1,0.1, 0.1,0.1,'figaro',@id_article);
