DROP PROCEDURE IF EXISTS PBELONG;
DELIMITER |
CREATE PROCEDURE PBELONG (IN VID_ARTICLE INT, IN VLABEL VARCHAR(25))
BEGIN

    DECLARE VID_LABEL INT DEFAULT 0;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VID_LABEL = NULL;

    SELECT label.id_label INTO VID_LABEL
    FROM label
    WHERE label.label = VLABEL;

    IF (VID_LABEL IS NULL)  THEN
        INSERT INTO label (id_label, label) VALUES (NULL,VLABEL);
        SELECT LAST_INSERT_ID() INTO VID_LABEL;
    END IF;


    INSERT INTO belong (id_article,id_label) VALUES (VID_ARTICLE ,VID_LABEL);

END|         

DELIMITER ;
