DROP PROCEDURE IF EXISTS PLABEL;
DELIMITER |
CREATE PROCEDURE PLABEL (IN VLABEL VARCHAR(50))
BEGIN
     INSERT INTO label (id_label,label) VALUES (NULL,VLABEL);
END|

DELIMITER ;
CALL PLABEL("SPORT");
CALL PLABEL("HUMOUR");