DROP PROCEDURE IF EXISTS PPOS_TAGGING;

DELIMITER |

CREATE PROCEDURE PPOS_TAGGING (IN VPOS_TAG VARCHAR(25))   
BEGIN
	INSERT INTO pos_tagging (id_pos_tag, pos_tag) VALUES (NULL,VPOS_TAG);

END|         

DELIMITER ;

CALL PPOS_TAGGING('adjectif');