DROP PROCEDURE IF EXISTS PREALIZE;
DELIMITER |
CREATE PROCEDURE PREALIZE (IN VID_AUTOR INT, IN VID_ARTICLE INT)   
BEGIN
	 
     INSERT INTO realize (id_author, id_article) VALUES (VID_AUTOR ,VID_ARTICLE);

END|         

DELIMITER ;

CALL PREALIZE(1,2);