DELIMITER /
DROP PROCEDURE IF EXISTS PAUTEUR/

CREATE PROCEDURE PAUTEUR (IN VNOM_AUTEUR VARCHAR(50), IN VPRENOM_AUTEUR VARCHAR(50), OUT VID_AUTEUR INT)   
BEGIN
     INSERT INTO AUTEUR (ID_AUTEUR, NOM_AUTEUR, PRENOM_AUTEUR) VALUES (NULL, VNOM_AUTEUR,VPRENOM_AUTEUR);
     SELECT LAST_INSERT_ID() INTO VID_AUTEUR;
END/

CALL PAUTEUR("jean","mich",@VID_AUTEUR)/
CALL PAUTEUR("be","fi",@VID_AUTEUR)/
SELECT @VID_AUTEUR/