DROP PROCEDURE IF EXISTS PBELONG;
DELIMITER |
CREATE PROCEDURE PBELONG (IN VID_ARTICLE INT, IN VID_CLASS INT)   
BEGIN
	 
     INSERT INTO BELONG VALUES (VID_ARTICLE ,VID_CLASS);

END|         

DELIMITER ;