DROP PROCEDURE IF EXISTS PCLASSIFICATION;
DELIMITER |
CREATE PROCEDURE PCLASSIFICATION (IN VCLASS VARCHAR(50))
BEGIN
     INSERT INTO CLASSIFICATION VALUES (NULL,VCLASS);
END|

DELIMITER ;
CALL PCLASSIFICATION("SPORT");
CALL PCLASSIFICATION("HUMOUR");

