DROP PROCEDURE IF EXISTS PENTITE;
DELIMITER |
CREATE PROCEDURE PENTITE (IN VENTITE VARCHAR(50))   
BEGIN
     INSERT INTO ENTITE VALUES (NULL,VENTITE);
END|         

DELIMITER ;
CALL PENTITE("PERSONNE");
CALL PENTITE("LIEU");

