DROP PROCEDURE IF EXISTS PPOSITION_WORD;
DELIMITER |
CREATE PROCEDURE PPOSITION_WORD (IN VPOSITION INT, IN VTITLE BOOLEAN, IN VWORD VARCHAR(50), VTYPE_ENTITY VARCHAR(25), IN VPOS_TAG VARCHAR(25), IN VID_ARTICLE INT,IN VFILE_WIKI VARCHAR(255))   

BEGIN
	DECLARE VID_WORD INT;
     DECLARE VID_ENTITY INT; 
     DECLARE VID_POS_TAG INT;
     DECLARE VID_WIKI INT;
     
     SELECT ID_WORD INTO VID_WORD
     FROM WORD
     WHERE WORD = VWORD;
     
     SELECT ID_ENTITY INTO VID_ENTITY
     FROM ENTITY
     WHERE TYPE_ENTITY = VTYPE_ENTITY;
     
     SELECT ID_POS_TAG INTO VID_POS_TAG
     FROM POS_TAGGING
     WHERE POS_TAG = VPOS_TAG;
     
     SELECT ID_WIKI INTO VID_WIKI
     FROM WIKI
     WHERE FILE_WIKI = VFILE_WIKI;

     INSERT INTO POSITION_WORD (ID_POSITION, POSITION,TITLE,ID_WORD,ID_ENTITY,ID_POS_TAG,ID_ARTICLE,ID_WIKI) 
     VALUES (NULL, VPOSITION,VTITLE,VID_WORD,VID_ENTITY,VID_POS_TAG,VID_ARTICLE,VID_WIKI);

END|         

DELIMITER ;
CALL PPOSITION_WORD(18,TRUE,"VBA","PERSONNE","adjectif",1,"wikipedia.org");
