
DROP PROCEDURE IF EXISTS PPOSITIONMOT;
DELIMITER |
CREATE PROCEDURE PPOSITIONMOT (IN VPOSITION INT, IN VTITRE BOOLEAN, IN VID_MOT INT, VID_ENTITE INT, IN VID_POS_TAG INT, IN VID_ARTICLE INT,IN VID_SYNONYME INT,IN VID_WIKI INT)   

BEGIN

     INSERT INTO POSITION_MOT (ID_POSITION, POSITION,TITRE,ID_MOT,ID_ENTITE,ID_POS_TAG,ID_ARTICLE,ID_SYNONYME,ID_WIKI) 
     VALUES (NULL, VPOSITION,VTITRE,VID_MOT,VID_ENTITE,VID_POS_TAG,VID_ARTICLE,VID_SYNONYME,VID_WIKI);

END|         

DELIMITER ;
CALL PPOSITIONMOT(1,TRUE,1,1,1,1,1,1);
CALL PPOSITIONMOT(2,FALSE,2,1,1,1,1,1);
