  DELIMITER |
  CREATE TRIGGER TPOSTAG BEFORE INSERT
  ON POS_TAGGING FOR EACH ROW
  BEGIN
       DECLARE CAPACITY_ERROR CONDITION FOR SQLSTATE '99991';  
       SIGNAL CAPACITY_ERROR SET MESSAGE_TEXT = 'the key cannot be empty';
       IF (id__pos_tag is NULL) THEN
		SIGNAL CAPACITY_ERROR;
	   END IF;

  END |
  DELIMITER ;