DELIMITER |
CREATE TRIGGER TARTICLE BEFORE INSERT
ON ARTICLE FOR EACH ROW

BEGIN

   DECLARE counter1 int;
   DECLARE CLE_ETRANGERE CONDITION FOR SQLSTATE '99997';

   SELECT COUNT(N.id_newspaper) INTO counter1
   FROM NEWSPAPER N
   WHERE NEW.id_newspaper IN (SELECT id_newspaper FROM NEWSPAPER);

   IF (counter1=0)  THEN
	 SIGNAL CLE_ETRANGERE SET MESSAGE_TEXT = "NEWSPAPER's Foreign key does not exist";
   END IF;
END |
DELIMITER ;