DELIMITER /
DROP PROCEDURE IF EXISTS pauthor/

CREATE PROCEDURE pauthor (IN VID_ARTICLE INT, IN VSURNAME_AUTHOR VARCHAR(50), IN VFIRSTNAME_AUTHOR VARCHAR(50))   
BEGIN
	
	DECLARE COUNT_ID INT DEFAULT 0;
	DECLARE VID_AUTHOR INT DEFAULT 0;
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET VID_AUTHOR = NULL;

	SELECT author.id_author INTO VID_AUTHOR
	FROM author 
	WHERE author.surname_author = VSURNAME_AUTHOR
	AND author.firstname_author = VFIRSTNAME_AUTHOR;

	IF (VID_AUTHOR IS NULL)  THEN 
		INSERT INTO author (id_author, surname_author, firstname_author) VALUES (NULL, VSURNAME_AUTHOR,VFIRSTNAME_AUTHOR);
    	SELECT LAST_INSERT_ID() INTO VID_AUTHOR;
	END IF;
	
    INSERT INTO realize (id_author, id_article) VALUES (VID_AUTHOR ,VID_ARTICLE);

END/

DELIMITER ;

CALL pauthor('1', 'MICKA', 'ANJ');