DROP PROCEDURE IF EXISTS pbelong;
DELIMITER |
CREATE PROCEDURE pbelong (IN VID_ARTICLE INT, IN VID_LABEL INT)   
BEGIN
	 
     INSERT INTO belong (id_article,id_label) VALUES (VID_ARTICLE ,VID_LABEL);

END|         

DELIMITER ;
